// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Article struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Url         string     `json:"url"`
	Title       string     `json:"title"`
	Author      string     `json:"author"`
	Content     string     `json:"content"`
	Summary     string     `json:"summary"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ArticleState struct {
	UserID    string     `json:"user_id"`
	ArticleID int64      `json:"article_id"`
	IsRead    int64      `json:"is_read"`
	IsStarred int64      `json:"is_starred"`
	ReadAt    *time.Time `json:"read_at"`
	StarredAt *time.Time `json:"starred_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	SortOrder int64     `json:"sort_order"`
}

type Feed struct {
	ID           int64      `json:"id"`
	UserID       string     `json:"user_id"`
	CategoryID   *int64     `json:"category_id"`
	Url          string     `json:"url"`
	Title        string     `json:"title"`
	SiteUrl      string     `json:"site_url"`
	Description  string     `json:"description"`
	LastUpdated  *time.Time `json:"last_updated"`
	LastError    *string    `json:"last_error"`
	CreatedAt    time.Time  `json:"created_at"`
	SortOrder    int64      `json:"sort_order"`
	Etag         string     `json:"etag"`
	LastModified string     `json:"last_modified"`
	ErrorCount   int64      `json:"error_count"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
